version: '3.9'
services:
  node:
    build:
      context: .
      dockerfile: ./node.Dockerfile
    env_file:
      - .env.local
    command: npm run dev
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"